# Generated by Django 3.1.1 on 2020-09-17 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('publishing_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnails_urls', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
