# Generated by Django 3.1.1 on 2020-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videodata',
            index=models.Index(fields=['title', 'description'], name='youtube_vid_title_4bc413_idx'),
        ),
        migrations.AddIndex(
            model_name='videodata',
            index=models.Index(fields=['-publishing_datetime'], name='youtube_vid_publish_d0985f_idx'),
        ),
    ]
